# MD013: Line length
# We are more permissive on line length, especially in code blocks and tables.
default: true

MD013:
  line_length: 120
  code_blocks: false
  tables: false

MD033:
  allowed_elements:
    - table
    - tr
    - th
    - td
    - style
    - img
    - i
